sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 16
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then npm run ghpages; fi
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/angular-dynamic-forms
  github_token: $PUSH_TOKEN
  on:
    branch: master
