sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - stable
before_install:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then npm run ghpages; fi
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/angular-dynamic-forms
  github_token: $PUSH_TOKEN
  on:
    branch: master
